version: '3'
services:
  bot:
    build: ~/bot
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  api:
    build: ~/api
    ports:
      - "3050:3050"

  ym_api:
    build: ~/ym-api
    ports:
      - "5050:5050"

volumes:
  redis-data: